Repository TheCodexProject/TheCodexProject-BackEnd, pull requests merged in 2024-09, with the labels that each got.

#4 Feature project
  .gitignore
  src/core/domain/exceptions/Project/ProjectDescription/ProjectDescriptionTooLongException.cs
  src/core/domain/exceptions/Project/ProjectStatus/ProjectStatusEmptyException.cs
  src/core/domain/exceptions/Project/ProjectTitle/ProjectTitleEmptyException.cs
  src/core/domain/exceptions/Project/ProjectTitle/ProjectTitleTooLongException.cs
  src/core/domain/exceptions/Project/ProjectTitle/ProjectTitleTooShortException.cs
  src/core/domain/exceptions/Project/TimeRange/ProjectTimeRangeEndBeforeStartException.cs
  src/core/domain/exceptions/Project/TimeRange/ProjectTimeRangeStartAfterEndException.cs
  src/core/domain/exceptions/RequiredFieldMissingException.cs
  src/core/domain/models/Project/Project.cs
  src/core/domain/models/Project/ProjectBuilder.cs
  src/core/domain/models/Project/ProjectConstants.cs
  src/core/domain/models/Project/values/ProjectDescription.cs
  src/core/domain/models/Project/values/ProjectMethodology.cs
  src/core/domain/models/Project/values/ProjectPriority.cs
  src/core/domain/models/Project/values/ProjectStatus.cs
  src/core/domain/models/Project/values/ProjectTimeRange.cs
  src/core/domain/models/Project/values/ProjectTitle.cs
  src/tests/Unit/Unit.csproj
  src/tests/Unit/common/ProjectBuilderTests.cs
  src/tests/Unit/values/Project/ProjectDescriptionTests.cs
  src/tests/Unit/values/Project/ProjectTimeRangeTests.cs
  src/tests/Unit/values/Project/ProjectTitleTests.cs
Labels: Feature

#3 Feature workspace
  src/core/domain/domain.csproj
  src/core/domain/exceptions/Workspace/WorkspaceTitle/WorkspaceTitleEmptyException.cs
  src/core/domain/exceptions/Workspace/WorkspaceTitle/WorkspaceTitleTooLongException.cs
  src/core/domain/exceptions/Workspace/WorkspaceTitle/WorkspaceTitleTooShortException.cs
  src/core/domain/interfaces/IBuilder..cs
  src/core/domain/models/Interfaces/IResource.cs
  src/core/domain/models/Workspace/Workspace.cs
  src/core/domain/models/Workspace/WorkspaceBuilder.cs
  src/core/domain/models/Workspace/WorkspaceConstants.cs
  src/core/domain/models/Workspace/values/WorkspaceTitle.cs
  src/tests/Unit/Unit.csproj
  src/tests/Unit/models/WorkSpace/WorkspaceBuilderTests.cs
  src/tests/Unit/values/WorkSpace/WorkSpaceTitleTests.cs
Labels: Feature

#1 Improvements to WorkItem
  TheCodexProject-BackEnd.sln.DotSettings.user
  src/core/domain/exceptions/Id/IdConversionExpection.cs
  src/core/domain/interfaces/IBuilder.cs
  src/core/domain/models/WorkItem/WorkItem.cs
  src/core/domain/models/WorkItem/WorkItemBuilder.cs
  src/core/domain/models/WorkItem/WorkItemConstants.cs
  src/core/domain/models/shared/Id.cs
  src/core/domain/models/shared/Metadata.cs
  src/tests/Unit/Unit.csproj
  src/tests/Unit/models/WorkItem/WorkItemBuilderTests.cs
Labels: Improvement

#2 Improvement user
  src/core/domain/models/User/User.cs
  src/core/domain/models/User/UserBuilder.cs
  src/core/domain/models/User/UserConstants.cs
  src/core/domain/models/User/values/Email.cs
  src/core/domain/models/User/values/FirstName.cs
  src/core/domain/models/User/values/LastName.cs
  src/core/domain/models/Users/User.cs
  src/tests/Unit/models/User/UserBuilderTests.cs
  src/tests/Unit/values/User/EmailTests.cs
  src/tests/Unit/values/User/FirstNameTests.cs
  src/tests/Unit/values/User/LastNameTests.cs
Labels: Improvement

#5 Improvement to Ids.
  src/core/domain/models/Project/Project.cs
  src/core/domain/models/Workspace/Workspace.cs
  src/tests/Unit/Unit.csproj
  src/tests/Unit/models/Project/ProjectBuilderTests.cs
  src/tests/Unit/values/Shared/IdTests.cs
Labels: Improvement

#6 Initial EF core setup.
  .gitignore
  TheCodexProject-BackEnd.sln
  src/Infrastructure/EFCorePersistence/ApplicationDbContext.cs
  src/Infrastructure/EFCorePersistence/ApplicationDbContextFactory.cs
  src/Infrastructure/EFCorePersistence/Config/UserConfiguration.cs
  src/Infrastructure/EFCorePersistence/Config/WorkItemConfiguration.cs
  src/Infrastructure/EFCorePersistence/EFCorePersistence.csproj
  src/Infrastructure/EFCorePersistence/Migrations/20240923072034_InitialCreate.Designer.cs
  src/Infrastructure/EFCorePersistence/Migrations/20240923072034_InitialCreate.cs
  src/Infrastructure/EFCorePersistence/Migrations/ApplicationDbContextModelSnapshot.cs
  src/Infrastructure/EFCorePersistence/Repositories/Repository.cs
  src/Infrastructure/EFCorePersistence/appsettings.json
  src/core/domain/domain.csproj
  src/core/domain/interfaces/IRepository.cs
  src/core/domain/models/Project/values/ProjectDescription.cs
  src/core/domain/models/Project/values/ProjectTitle.cs
  src/core/domain/models/WorkItem/values/WorkItemDescription.cs
  src/core/domain/models/WorkItem/values/WorkItemTitle.cs
  src/core/domain/models/Workspace/values/WorkspaceTitle.cs
Labels: Feature

#13 The test was expecting a different exception in IterationBuilderTests
  src/tests/Unit/models/Iteration/IterationBuilderTests.cs
Labels: Bug

#10 Feature organisation
  TheCodexProject-BackEnd.sln.DotSettings.user
  src/core/domain/exceptions/Organisation/OrganisationDocumentationAlreadyExistsException.cs
  src/core/domain/exceptions/Organisation/OrganisationDocumentationNotFoundException.cs
  src/core/domain/exceptions/Organisation/OrganisationName/OrganisationNameEmptyException.cs
  src/core/domain/exceptions/Organisation/OrganisationName/OrganisationNameTooLongException.cs
  src/core/domain/exceptions/Organisation/OrganisationName/OrganisationNameTooShortException.cs
  src/core/domain/exceptions/Organisation/OrganisationNeedsAnOwnerException.cs
  src/core/domain/exceptions/Organisation/OrganisationOwnerAlreadyExistsException.cs
  src/core/domain/exceptions/Organisation/OrganisationOwnerNotFoundException.cs
  src/core/domain/exceptions/Workspace/WorkspaceOwnerEmptyException.cs
  src/core/domain/models/Interfaces/IOwnership.cs
  src/core/domain/models/Organisation/Organisation.cs
  src/core/domain/models/Organisation/OrganisationBuilder.cs
  src/core/domain/models/Organisation/values/OrganisationName.cs
  src/core/domain/models/User/User.cs
  src/core/domain/models/Workspace/Workspace.cs
  src/core/domain/models/Workspace/WorkspaceBuilder.cs
  src/core/domain/models/Workspace/WorkspaceConstants.cs
  src/tests/Unit/models/Organisation/OrganisationBuilderTests.cs
  src/tests/Unit/models/WorkSpace/WorkspaceBuilderTests.cs
  src/tests/Unit/values/Organisation/OrganisationNameTests.cs
Labels: Feature

#11 Improvement workitem
  src/core/domain/exceptions/WorkItem/DepedencyAlreadyExistsException.cs
  src/core/domain/exceptions/WorkItem/DependencyNotFoundException.cs
  src/core/domain/exceptions/WorkItem/DocumentationAlreadyExistsException.cs
  src/core/domain/exceptions/WorkItem/DocumentationNotFoundException.cs
  src/core/domain/exceptions/WorkItem/MetadataAlreadyInitializedException.cs
  src/core/domain/exceptions/WorkItem/SubItemAlreadyExistsException.cs
  src/core/domain/exceptions/WorkItem/SubItemNotFoundException.cs
  src/core/domain/exceptions/WorkItem/UserNotFoundException.cs
  src/core/domain/models/WorkItem/WorkItem.cs
  src/core/domain/models/WorkItem/WorkItemBuilder.cs
  src/core/domain/models/WorkItem/WorkItemConstants.cs
  src/tests/Unit/models/WorkItem/WorkItemBuilderTests.cs
Labels: Improvement
